### ISSUE TITLE
"Tabs that cover the entire width of the tab bar" underline doesn't cover entire width

### ISSUE THREAD

**Issue by samiheikki** [vaadin/vaadin-tabs#68] opened 2017-12-17 11:18 UTC
Demo: https://cdn.vaadin.com/vaadin-tabs/2.0.0-alpha1/demo/#tabs-basic-demos

<img width="861" alt="screen shot 2017-12-17 at 12 16 46" src="https://user-images.githubusercontent.com/8615573/34078988-ca2ab0f2-e32c-11e7-9f3c-efcb48a71619.png">

**Comment by jouni** [comment] 2017-12-23 20:47
This should be fixed now in master, after the latest Valo updates.

**Closed by jouni** 2017-12-23 20:47 UTC

**Comment by jouni** [comment] 2017-12-23 20:49
I mean, the text is now centered as it should. The underline has a max-width, so it should not cover the entire width by design.
